name: Metrics

on:
  schedule:
    - cron: "0 */6 * * *"
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          user: DelTa-0
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kathmandu
